### ISSUE TITLE
Hot reload is not working

### ISSUE THREAD

**Issue by gmsorrow** [bertho-zero/react-redux-universal-hot-example#482] opened 2018-09-26 10:38 UTC
Hello.
New installed repo has broken hot reload.
![image](https://user-images.githubusercontent.com/12304143/46074710-08642680-c191-11e8-9899-f1d16d53434e.png)

**Comment by MikhailLoginov** [comment] 2018-09-27 14:12
It looks like I have the same problem as well. Does anybody know how to avoid it?

**Comment by bertho-zero** [comment] 2018-09-27 19:06
What exactly are you doing to get there? I can not reproduce that.

**Comment by green122** [comment] 2018-09-28 08:38
I've got the same problem. And i got there just after installing the boilerplate form the scratch. It makes hot reloading for styles but not for code. Just change one letter and save - and i've got the same message in a browser. Project works ok after manual reloading but HMR seems to be broken.

**Comment by gmsorrow** [comment] 2018-09-28 09:07
> he same problem. And i got there just after installing the boilerplate form the scratch. It makes hot reloading for styles but not for code. Just change one letter and save - and i've got the same message in a

Agreed.
The easiest way to reproduce:
- install repo
- npm run dev / yarn dev
- change 1 letter in text on home page
- save changes to trigger HMR

**Comment by bertho-zero** [comment] 2018-09-28 21:04
Fixed in https://github.com/bertho-zero/react-redux-universal-hot-example/commit/2b1942c85dd91893e9a1688ceede0e9193649741

**Closed** 2018-09-28 21:11 UTC

**Comment by gmsorrow** [comment] 2018-10-01 10:03
Thank  you, @bertho-zero!
